# Generated by Django 5.0.6 on 2024-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Dept', 'Dept')], default='Clean', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Commercial', 'Commercial'), ('Government', 'Government')], default='Personal', max_length=10),
        ),
    ]
