# Generated by Django 5.0.6 on 2024-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_vehicle_status_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Dept', 'Dept')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Commercial', 'Commercial'), ('Government', 'Government')], max_length=10),
        ),
    ]
